### ISSUE TITLE
Get borrowed ROV to work

### ISSUE THREAD

**Issue by MFauzanAP** [QU-RoboSub/2025-general#5]

**Comment by MFauzanAP** [comment]
Testing discord updates for multi-subsystem tasks.

**Comment by MFauzanAP** [comment]
An update regarding the ROV, the batteries are apparently not charged and also have a weird smell coming from them (need to double check again). We need to try find a charger for these and see if they can still be used or if we need to buy new batteries.

![20240619_213614.jpg](https://github.com/QU-RoboSub/2025-general/assets/85939000/23bb9cf5-81e3-4e86-9c6d-53b09bd2dd41)

![20240619_213623.jpg](https://github.com/QU-RoboSub/2025-general/assets/85939000/ac545560-a4cd-4698-8d0f-cd07c09a4796)

![20240619_213559.jpg](https://github.com/QU-RoboSub/2025-general/assets/85939000/9c7c4d43-efd6-4fe4-9f5e-39bddf707e78)

**Comment by Saad-Mohamed-Aden** [comment]
![image](https://github.com/QU-RoboSub/2025-general/assets/172346781/ec8eb583-4d0a-45e8-9e49-d0120eb52fde)
we could use this battery charger 
which I was planning anyway to put in the list 

and for the smell, I think it is better to not use these batteries, because batteries are generally dangerous, especially li ion and lipo
and smell could indicate that something is leaking so forget about using those
we could use this 
![image](https://github.com/QU-RoboSub/2025-general/assets/172346781/d07af956-99cf-4f03-8661-d7ca6c4f3dc9)

 but 
1-it does have smaller capacity which mean less time in water 
2-the size for it is bigger than the one in the picture (which means changing the design)


or we could find another battery with the same size (26650) or we could buy it from the compeny which i do not think they would be able to ship it to us
![image](https://github.com/QU-RoboSub/2025-general/assets/172346781/cde1c9da-04cc-499c-bdc5-aed8055c7a40)

**Comment by MFauzanAP** [comment]
> we could use this battery charger

Oh actually I remember seeing some of these (charger + battery) lying around in QU, maybe we could test to see if 3 of them can fit in the tube, if it can I guess we replace the current batteries w the green one.

But I don't think we should spend too much on these since it's only to get the openrov up and running. If you have these batteries already, I can bring the ROV to you in the next meeting so we can test. If not, I'll try contact someone who might have them and see if he can let us have a few.

**Comment by MFauzanAP** [comment]
No need for this anymore.
